function colors = autocolor(num_colors, idx)
% function colors = autocolor(num_colors)
% returns a num_colors x 3 matrix

% number of different colors you need 
% (as many as lines you are planning to plot)

colors = resample(jet,num_colors,64);

%find neg num and num>1 generated by the interpolation mechanism used by
% resampe
neg = find(colors<0);
colors(neg)= 0;
too_big = find(colors>1);
colors(too_big) = 1;