num_colors = 26; % number of different colors you need 
                 % (as many as lines you are planning to plot)

colors = resample(jet,num_colors,64);

%find neg num and num>1 generated by the interpolation mechanism used by
% resampe
neg = find(colors<0);
colors(neg)= 0;
too_big = find(colors>1);
colors(too_big) = 1;

figure
hold on
for m = 1 : num_colors,
    h(m) = plot([1 2 3],[m m+1 m+2]); % just plotting parallel lines as an example
    set(h(m),'Color',colors(m,:))
end