function current_proj = proj_conditions(current_proj)
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

if current_proj.valid == 0,
   return;
end;

% load data from project into "backing store"
cond_array = [];
pad = '                                                                               ';
for i=1:size(current_proj.conditions_cells, 1),
   name = current_proj.conditions_cells(i,1);
   scene_name = current_proj.conditions_cells(i,2);
   cond_string = sprintf('%s%s%s', name, pad(1:(30 - length(name))),scene_name);
   cond_array = strvcat(cond_array, cond_string);
end;
cond_cells = cellstr(cond_array);
load proj_conditions

h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','E:\Matlab\bin\proj_conditions.m', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[332.25 387.75 414.75 189], ...
	'Tag','Fig5', ...
	'ToolBar','none');
current_proj.prjui.conditions_listbox = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
   'Position',[13.5 50.25 312 89.25], ...
	'String', cond_array, ...
	'Style','listbox', ...
	'Tag','Listbox3', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[341.25 123 57.75 27.75], ...
	'String','OK', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[341.25 87 57.75 27.75], ...
	'String','Apply', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[341.25 51 57.75 27.75], ...
	'String','Cancel', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[21 141 121.5 16.5], ...
	'String','Condition Name', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[174.75 141 121.5 16.5], ...
	'String','Scene File  Name', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
   'Position',[16.5 16.5 68.25 19.5], ...
   'Callback', 'proj_cond_new', ...
	'String','New...', ...
	'Tag','Pushbutton2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[90 16.5 63.75 19.5], ...
	'String','Edit...', ...
	'Tag','Pushbutton2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[158.25 16.5 59.25 19.5], ...
	'String','Delete...', ...
	'Tag','Pushbutton2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[448.5 144.75 57.75 27.75], ...
	'String','Cancel', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[246.75 16.5 81 19.5], ...
	'String','Import...', ...
	'Tag','Pushbutton2');
if nargout > 0, fig = h0; end
