function project = proj_newcond_dlg(project)
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.
if project.valid < 1
   return;
end;
load proj_newcond_dlg
scenes = unique(project.session_info.scene_names);
h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','E:\Matlab\bin\proj_newcond_dlg.m', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[348.75 247.5 420 143.25], ...
	'Tag','Fig3', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
   'Position',[348 27 57.75 27.75], ...
   'Callback', 'current_proj = newcond_close(current_proj, 0);', ...
	'String','Cancel', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
   'Position',[348 63 57.75 27.75], ...
   'Callback', 'current_proj = newcond_close(current_proj, -1);', ...
	'String','Apply', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
   'Position',[348 99 57.75 27.75], ...
   'Callback', 'current_proj = newcond_close(current_proj, 1);', ...
	'String','OK', ...
	'Tag','Pushbutton1');
popup = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[69.75 19.5 170.25 24.75], ...
	'String',scenes, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu1', ...
	'Value',1);
newcond_editbox = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
   'Position',[68.25 79.5 170.25 22.5], ...
   'Max', 1, ...
   'Min', 3, ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[79.5 106.5 140.25 18.75], ...
	'String','Condition Name', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[76.5 48.75 151.5 18.75], ...
	'String','Scene Name', ...
	'Style','text', ...
   'Tag','StaticText2');
project.prjui.newcond_editbox = newcond_editbox;
project.prjui.newcond_scene_popup = popup;
project.prjui.newcond_fig = h0;
if nargout > 0, fig = h0; end
