% This gui package allows you to load Kinematix raw data files (*.vr) into Matlab,
% and make some nice 3D plots.
%
% Just type "showdata" without the quotes, and you will get a nice GUI. Here are the
% steps to follow:
%
% 1. Load your data file - If the raw data file that you want to plot begins with a
%    number "001_1.vr" for example, you must either copy it to another file whose name
%    begins with a letter ("m001_1.vr") or temporarily rename the file while working
%    with this package. We regret the inconvenience! Then press the "Load Data File"
%    button and navigate to your raw data files (in the Kelsr\Data folder), and press "OK".
%
% 2. Now that your file is loaded, you can choose a title for your plot, and control the
%    axes layout (type "help axes" in Matlab).
%
% 3. You can see in the "current file info" window how many trials are in the data file, how
%    many and which sensors are available, and how many teacher recordings there are. Directly
%    below that is a drop-down list that shows the scenes, and which trial numbers are in which
%    scene.
%
% 4. Now you are ready to choose which trials you want to plot. You can enter numbers separated
%    by spaces for each trial you want to include in a plot, and/or you can specify ranges for
%    the first and last trials (1:10 plots trials 1 through 10), and combinations of the two formats.
%    Sensor number specification is the same.
%
% 5. You can also select a number of Teacher recordings to plot. These correspond to the scenes that
%    are listed in the drop-down list in the "info" area. You can specify which teachers to plot in
%    the same manner as the trials described in Section 4.
%
% 6. Now press "Plot Selected Trial(s)" and see what happens. If you did everything right, you should
%    get a nice 3D plot with different colored traces for each sensor. Also, the transmitter is displayed
%    at the (0, 0, 0) coordinate. Currently, the Teacher plots are in the same color scheme as the regular
%    trials, which is admittedly not optimal.
%
% 7. You can display several plots at once by pressing "Start New Figure" and specifying another plot.
%
% Have fun!


h0 = figure('Color',[0.1 0.1 0.7], ...
	'MenuBar','none', ...
	'Name','Data Visualization Control Panel', ...
	'NumberTitle','off', ...
	'Position',[493 253 459 460], ...
	'Tag','Fig1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'ListboxTop',0, ...
	'Position',[28.5 30.75 283.5 108.75], ...
	'Style','frame', ...
	'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'ListboxTop',0, ...
	'Position',[30 156 283.5 104.25], ...
	'Style','frame', ...
	'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','loadfile;', ...
	'ListboxTop',0, ...
	'Position',[39.75 228.75 81.75 20.25], ...
	'String','Load Data File', ...
	'Tag','Pushbutton5');
trialbox = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[116.25 105 93 18.75], ...
	'Style','edit', ...
	'Tag','Trial');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'ListboxTop',0, ...
	'Position',[35.25 106.5 72.75 16.5], ...
	'String','Trial Number(s)', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'ListboxTop',0, ...
	'Position',[36 75 73.5 17.25], ...
	'String','Sensor Number(s)', ...
	'Style','text', ...
	'Tag','StaticText2');
sensorbox = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[117 74.25 93 18.75], ...
	'Style','edit', ...
	'Tag','Sensor');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','fig = figure(''number'',''off'',''name'',''Plot'');', ...
	'ListboxTop',0, ...
	'Position',[223.5 103.5 82.5 21], ...
	'String','Start New Figure', ...
	'Tag','Pushbutton4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','help showdata', ...
	'ListboxTop',0, ...
	'Position',[129.75 228.75 81.75 21], ...
	'String','Display Help', ...
	'Tag','Pushbutton3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','quit;', ...
	'ListboxTop',0, ...
	'Position',[219.75 228.75 81.75 20.25], ...
	'String','Quit Matlab', ...
	'Tag','Pushbutton2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','plottrials', ...
	'ListboxTop',0, ...
	'Position',[224.25 73.5 82.5 20.25], ...
	'String','Plot Selected Trial(s)', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'ListboxTop',0, ...
	'Position',[40.5 195.75 79.5 18.75], ...
	'String','Current File Info', ...
	'Style','text', ...
	'Tag','StaticText3');
infobox = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'ListboxTop',0, ...
	'Position',[130.5 195 171 19.5], ...
	'Style','text', ...
	'Tag','Info');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[29.25 281.25 282 32.25], ...
	'Style','frame', ...
	'Tag','Frame2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'ListboxTop',0, ...
	'Position',[40.5 288 39.75 16.5], ...
	'String','Axes', ...
	'Style','text', ...
	'Tag','StaticText4');
axesbox = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[87 288 90.75 16.5], ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'ListboxTop',0, ...
	'Position',[188.25 287.25 39.75 16.5], ...
	'String','Title', ...
	'Style','text', ...
	'Tag','StaticText4');
titlebox = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[234.75 288 66 16.5], ...
	'Style','edit', ...
	'Tag','EditText1');
teacherbox = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[117 44.25 93 18.75], ...
	'Style','edit', ...
   'Tag','Teacher');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','plot_vels', ...
	'ListboxTop',0, ...
	'Position',[224.25 44.25 82.5 20.25], ...
	'String','Plot Velocities', ...
   'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','plot_arm', ...
	'ListboxTop',0, ...
	'Position',[224.25 14.25 82.5 20.25], ...
	'String','Plot Arm Data', ...
	'Tag','Pushbutton1');

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'ListboxTop',0, ...
	'Position',[36 45 73.5 17.25], ...
	'String','Teacher Number(s)', ...
	'Style','text', ...
	'Tag','StaticText5');
scenelist = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[39.75 165 262.25 19.5], ...
	'String',' ', ...
	'Style','popupmenu', ...
	'Tag','PopupMenu1', ...
	'Value',1);
arrowsbox = uicontrol('Parent',h0, ...
	'Units','points', ...
   'ListboxTop',0, ...
   'Style', 'checkbox', ...
	'Position',[36 14.25 112.5 14.25], ...
	'String','Plot Orientation arrows', ...
	'Tag','Arrowbox1');

% comment following for testing purposes
fig = figure('number','off','name','Plot');
num = 0;
name = '';
