% This gui package allows you to load Kinematix raw data files (*.vr) into Matlab,
% and make some nice 3D plots.
%
% Just type "showdata" without the quotes, and you will get a nice GUI. Here are the
% steps to follow:
%
% 1. Load your data file - If the raw data file that you want to plot begins with a
%    number "001_1.vr" for example, you must either copy it to another file whose name
%    begins with a letter ("m001_1.vr") or temporarily rename the file while working
%    with this package. We regret the inconvenience! Then press the "Load Data File"
%    button and navigate to your raw data files (in the Kelsr\Data folder), and press "OK".
%
% 2. Now that your file is loaded, you can choose a title for your plot, and control the
%    axes layout (type "help axes" in Matlab).
%
% 3. You can see in the "current file info" window how many trials are in the data file, how
%    many and which sensors are available, and how many teacher recordings there are. Directly
%    below that is a drop-down list that shows the scenes, and which trial numbers are in which
%    scene.
%
% 4. Now you are ready to choose which trials you want to plot. You can enter numbers separated
%    by spaces for each trial you want to include in a plot, and/or you can specify ranges for
%    the first and last trials (1:10 plots trials 1 through 10), and combinations of the two formats.
%    Sensor number specification is the same.
%
% 5. You can also select a number of Teacher recordings to plot. These correspond to the scenes that
%    are listed in the drop-down list in the "info" area. You can specify which teachers to plot in
%    the same manner as the trials described in Section 4.
%
% 6. Now press "Plot Selected Trial(s)" and see what happens. If you did everything right, you should
%    get a nice 3D plot with different colored traces for each sensor. Also, the transmitter is displayed
%    at the (0, 0, 0) coordinate. Currently, the Teacher plots are in the same color scheme as the regular
%    trials, which is admittedly not optimal.
%
% 7. You can display several plots at once by pressing "Start New Figure" and specifying another plot.
%
% Have fun!

function showdata_unified(selector)

if nargin == 0
    selector = 'init';
end

switch selector
case 'init'
    fig = figure('Color',[0.1 0.1 0.7], ...
        'MenuBar','none', ...
        'Name','Data Visualization Control Panel', ...
        'NumberTitle','off', ...
        'Position',[493 253 459 460], ...
        'Tag','Fig1');
    h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.752941 0.752941 0.752941], ...
        'ListboxTop',0, ...
        'Position',[28.5 30.75 283.5 108.75], ...
        'Style','frame', ...
        'Tag','Frame1');
    h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.752941 0.752941 0.752941], ...
        'ListboxTop',0, ...
        'Position',[30 156 283.5 104.25], ...
        'Style','frame', ...
        'Tag','Frame1');
    info.loadfile = uicontrol('Parent',h0, ...
        'Units','points', ...
        'Callback','showdata_unified(''loadfile'');', ...
        'ListboxTop',0, ...
        'Position',[39.75 228.75 81.75 20.25], ...
        'String','Load Data File', ...
        'Tag','Pushbutton5');
    info.trialbox = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[116.25 105 93 18.75], ...
        'Style','edit', ...
        'Tag','Trial');
    h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.9 0.9 0.9], ...
        'ListboxTop',0, ...
        'Position',[35.25 106.5 72.75 16.5], ...
        'String','Trial Number(s)', ...
        'Style','text', ...
        'Tag','StaticText1');
    h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.9 0.9 0.9], ...
        'ListboxTop',0, ...
        'Position',[36 75 73.5 17.25], ...
        'String','Sensor Number(s)', ...
        'Style','text', ...
        'Tag','StaticText2');
    info.sensorbox = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[117 74.25 93 18.75], ...
        'Style','edit', ...
        'Tag','Sensor');
    info.startnew = uicontrol('Parent',h0, ...
        'Units','points', ...
        'Callback','fig = figure(''number'',''off'',''name'',''Plot'');', ...
        'ListboxTop',0, ...
        'Position',[223.5 103.5 82.5 21], ...
        'String','Start New Figure', ...
        'Tag','Pushbutton4');
    h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'Callback','help showdata', ...
        'ListboxTop',0, ...
        'Position',[129.75 228.75 81.75 21], ...
        'String','Display Help', ...
        'Tag','Pushbutton3');
    h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'Callback','quit;', ...
        'ListboxTop',0, ...
        'Position',[219.75 228.75 81.75 20.25], ...
        'String','Quit Matlab', ...
        'Tag','Pushbutton2');
    h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'Callback','plottrials', ...
        'ListboxTop',0, ...
        'Position',[224.25 73.5 82.5 20.25], ...
        'String','Plot Selected Trial(s)', ...
        'Tag','Pushbutton1');
    h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.9 0.9 0.9], ...
        'ListboxTop',0, ...
        'Position',[40.5 195.75 79.5 18.75], ...
        'String','Current File Info', ...
        'Style','text', ...
        'Tag','StaticText3');
    infobox = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.9 0.9 0.9], ...
        'ListboxTop',0, ...
        'Position',[130.5 195 171 19.5], ...
        'Style','text', ...
        'Tag','Info');
    h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'ListboxTop',0, ...
        'Position',[29.25 281.25 282 32.25], ...
        'Style','frame', ...
        'Tag','Frame2');
    h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.9 0.9 0.9], ...
        'ListboxTop',0, ...
        'Position',[40.5 288 39.75 16.5], ...
        'String','Axes', ...
        'Style','text', ...
        'Tag','StaticText4');
    axesbox = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[87 288 90.75 16.5], ...
        'Style','edit', ...
        'Tag','EditText1');
    h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.9 0.9 0.9], ...
        'ListboxTop',0, ...
        'Position',[188.25 287.25 39.75 16.5], ...
        'String','Title', ...
        'Style','text', ...
        'Tag','StaticText4');
    titlebox = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[234.75 288 66 16.5], ...
        'Style','edit', ...
        'Tag','EditText1');
    teacherbox = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[117 44.25 93 18.75], ...
        'Style','edit', ...
        'Tag','Teacher');
    h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'Callback','plot_vels', ...
        'ListboxTop',0, ...
        'Position',[224.25 44.25 82.5 20.25], ...
        'String','Plot Velocities', ...
        'Tag','Pushbutton1');
    h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'Callback','plot_arm', ...
        'ListboxTop',0, ...
        'Position',[224.25 14.25 82.5 20.25], ...
        'String','Plot Arm Data', ...
        'Tag','Pushbutton1');
    
    h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.9 0.9 0.9], ...
        'ListboxTop',0, ...
        'Position',[36 45 73.5 17.25], ...
        'String','Teacher Number(s)', ...
        'Style','text', ...
        'Tag','StaticText5');
    scenelist = uicontrol('Parent',h0, ...
        'Units','points', ...
        'ListboxTop',0, ...
        'Position',[39.75 165 262.25 19.5], ...
        'String',' ', ...
        'Style','popupmenu', ...
        'Tag','PopupMenu1', ...
        'Value',1);
    arrowsbox = uicontrol('Parent',h0, ...
        'Units','points', ...
        'ListboxTop',0, ...
        'Style', 'checkbox', ...
        'Position',[36 14.25 112.5 14.25], ...
        'String','Plot Orientation arrows', ...
        'Tag','Arrowbox1');
    
case 'loadfile'
    [filename,pathname] = uigetfile('*.dat;*.vr;*.mat;*.prj','Open Data File');

if (pathname == 0),
   % 'cancel' condition
   return
else
   % want to always come back to the last directory
   cd(pathname);
   clear data;
   filename = lower(filename);
   
	% Prefix underscores with '\'
   undscr = findstr(filename,'_');
   if undscr>1,
      fname = filename;
      for i=1:length(undscr),
         name = sprintf('%s\\%s', fname(1:undscr(i)+i-2), fname(undscr(i)+(i-1):length(fname)));
         fname = name;
      end;
      clear(fname);
   else
      name = filename;
   end;   
   
   % this gets all the data, including the teachers, but they are not indexed
   clear newp;
   clear pload;
   if findstr(filename, '.prj') > 0,
      % have project file, set flag
      pload = 1;
      % this gets all the data, including the teachers, but they are not indexed
      newp = load(strcat(pathname, filename), '-MAT');
      newp = newp.current_proj;
      newp.filename = filename;
      newp.pathname = pathname;
      
      session_info = newp.session_info;
      data = newp.data;
      ii = newp.ii;
      iif = newp.iif;
      tch_start = newp.tch_start;
   	tch_end = newp.tch_end;
      num = newp.num;
      sens = newp.sens;
      scene_info = newp.scene_info;
      num_teachers = newp.num_teachers;      
      
   else,
      
      data = load([pathname filename]);
      
      
      
      %eval(sprintf('data = %s;',num2str(name)));
      %clear(name);
      % ii and iif are the beginnings and ends of the trials, respectively
      ii = find(data(:,1)==-1003);
      iif = find(data(:,1)==-1004);
      % tch_start and tch_end are the beginnings and ends of the teacher recordings
      tch_start = find(data(:,1)==-1001);
      tch_end = find(data(:,1)==-1002);
      % num is the number of trials
      num = length(ii);
      % num_teachers is the number of teachers
      num_teachers = length(tch_start);
      
      sens = [];
      if ~isempty(find(data(:,1)==1)), 
         sens = [sens ' 1']; 
      end;
      
      if ~isempty(find(data(:,1)==2)), 
         sens = [sens ' 2']; 
      end;
      
      if ~isempty(find(data(:,1)==3)), 
         sens = [sens ' 3']; 
      end;
      
      if ~isempty(find(data(:,1)==4)), 
         sens = [sens ' 4']; 
      end;
      
      % call load_scene_data to get teacher and scene name info
      [num_scenes, scene_info, session_info] = load_scene_data(filename, data, ii, tch_start );
      session_info.data = data;
      session_info.sensor_string = sens;
      session_info.trial_start = ii;
      session_info.trial_end = iif;
      session_info.tch_start = tch_start;
      session_info.tch_end = tch_end;
   end;
   
   % fix for missing sensor 4 data -- comment out following 6 lines with %-sign at beg. of line
   session_info = fix_pour_data(session_info);
   data = session_info.data;
   ii = session_info.trial_start;
   iif = session_info.trial_end;
   tch_start = session_info.tch_start;
   tch_end = session_info.tch_end;
   
   % calculate some stats! -- radius set really high to get all samples
   session_info = dana_targets(session_info);
   if session_info.orient_valid
       session_info = dana_spatial_error(session_info);
       session_info = dana_orient_error(session_info);
   end
   [sr, session_info] = spill_stats(session_info, 10.395, 8.5, 10.495, 7.0, 6.2);
   
   eval(sprintf('sensors = [%s];',session_info.sensor_string));
   sensors = sensors(find((sensors<=4) & (sensors>=1)));
   if find(sensors==2) & find(sensors==3),
      %have arm sensor data
      if exist('pload')
         % loaded a project
      	% ask if we want to reload the arm
      	if isfield(session_info,'has_arm')
         	if session_info.has_arm
            	if strcmp('Yes', questdlg('Recalculate Arm data? Could take awhile!', 'Question!', 'Yes', 'No','Yes'))
                  session_info = dana_calc_arm(session_info);
                  newp.session_info = session_info;
                  current_proj = newp;
                  save(strcat(newp.pathname, newp.filename), 'current_proj');
               end
            end
         else
            if strcmp('Yes', questdlg('Calculate Arm data and save in this project? Could take awhile!', 'Question!', 'Yes', 'No', 'Yes'))
               session_info = dana_calc_arm(session_info);
               newp.session_info = session_info;
               current_proj = newp;
               save(strcat(newp.pathname, newp.filename), 'current_proj');
            end
         end
      else
         if strcmp('Yes', questdlg('Calculate Arm data for this session? Could take awhile!', 'Question!', 'Yes', 'No', 'Yes'))
            session_info = dana_calc_arm(session_info);
         end
		end
   end
   
   % set GUI controls to reflect results of file loading, clear GUI input boxes
   set(infobox,'string',sprintf('File: %s;   Trials: %d;   Sensors:%s   Teachers: %d',filename,num,sens,num_teachers));
   set(scenelist, 'Value', 1);
   set(scenelist, 'string', scene_info);
   set(trialbox,'string','');   
   set(sensorbox,'string','');
   set(teacherbox, 'string', '');
end

end
% comment following for testing purposes
fig = figure('number','off','name','Plot');
num = 0;
name = '';
